---
driver:
  name: vagrant

provisioner:
  always_update_cookbooks: true
  chef_license: accept
  name: chef_zero
  #nodes_path: test/fixtures/nodes
  product_name: chef
  product_version: 14.12

verifier:
  name: inspec

platforms:
  - name: eugenmayer/debian9
    driver:
      box: eugenmayer/debian9
      box_version: "9.3.0"
  - name: eugenmayer/debian10
    driver:
      box: eugenmayer/debian10
      box_version: "10.1.0"
      #gui: true

suites:
  - name: default
    run_list:
      - recipe[shorewall_ng_test::default]
    verifier:
      inspec_tests:
        - test/recipes/default
    attributes:
