---
driver:
  hostname: test # Hostname is used in the tests so should be fixed
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: debian-10
    driver:
      image: dokken/debian-10
      pid_one_command: /bin/systemd
      privileged: true

suites:
  - name: default
    run_list:
      - recipe[shorewall_ng_test::default]
    attributes:
  - name: with-snat
    run_list:
      - recipe[shorewall_ng_test::default]
    attributes:
      shorewall:
        snat:
          - action: SNAT(206.124.146.177)
            source: 172.20.1.0/29
            dest: eth0
            proto: tcp
            ports: smtp
