---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: eugenmayer/debian9
    driver:
      box: eugenmayer/debian9
      box_version: "9.1.6"
      gui: true

suites:
  - name: default
    run_list:
      - recipe[shorewall_ng_test::default]
    verifier:
      inspec_tests:
        - test/recipes/default
    attributes: